
set( PROTOCOLS_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/protocols )

set(

  PROTOCOLS_MODULE_COMMON_HEADERS_DIRECTORIES

  ## BASE PROTOCOL ##
  ${PROTOCOLS_MODULE_ROOT_DIR}/include/base_protocol

  ## DISCONNECT PROTOCOL ##
  ${PROTOCOLS_MODULE_ROOT_DIR}/include/disconnect_protocol

)

add_library(

  EXPORT_PROTOCOLS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_PROTOCOLS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${PROTOCOLS_MODULE_COMMON_HEADERS_DIRECTORIES}

)
