
set( PRIORITY_QUEUE_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/priority_queue )

set(

  PRIORITY_QUEUE_MODULE_COMMON_HEADERS_DIRECTORIES

  ${PRIORITY_QUEUE_MODULE_ROOT_DIR}/include/

)

add_library(

  EXPORT_PRIORITY_QUEUE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_PRIORITY_QUEUE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${PRIORITY_QUEUE_MODULE_COMMON_HEADERS_DIRECTORIES}

)
