
set( NODE_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/node )

set(

  NODE_MODULE_COMMON_HEADERS_DIRECTORIES

  ${NODE_MODULE_ROOT_DIR}/include

)

add_library(

  EXPORT_NODE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_NODE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${NODE_MODULE_COMMON_HEADERS_DIRECTORIES}

)
