
set( NODE_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/protocols )

set(

  NODE_MODULE_COMMON_HEADERS_DIRECTORIES

)

add_library(

  EXPORT_NODE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_NODE_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${PROTOCOLS_NODE_COMMON_HEADERS_DIRECTORIES}

)
