
set( NODE_MODULE_TESTS "node_module_tests" )
add_executable( ${NODE_MODULE_TESTS} ${CMAKE_CURRENT_LIST_DIR}/src/node_tests.cpp )
target_link_libraries( ${NODE_MODULE_TESTS} NODE_MODULE EXPORT_NODE_MODULE_COMMON_HEADERS_DIRECTORIES DIAGNOSTICS_MODULE EXPORT_DIAGNOSTICS_MODULE_COMMON_HEADERS_DIRECTORIES )
add_test( NODE_TESTS ${BUILD_BIN_DIR}/node_module_tests )
