
set( UTILS_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/utils )

set(

  UTILS_MODULE_COMMON_HEADERS_DIRECTORIES

  ## SMART POINTERS ##
  ${UTILS_MODULE_ROOT_DIR}/include/smart_pointers

)

add_library(

  EXPORT_UTILS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_UTILS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${UTILS_MODULE_COMMON_HEADERS_DIRECTORIES}

)
