
set( DIAGNOSTICS_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/diagnostics )

set(

  DIAGNOSTICS_MODULE_COMMON_HEADERS_DIRECTORIES

  ${DIAGNOSTICS_MODULE_ROOT_DIR}/include

)

add_library(

  EXPORT_DIAGNOSTICS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_DIAGNOSTICS_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${DIAGNOSTICS_MODULE_COMMON_HEADERS_DIRECTORIES}

)
