
set( COMMUNICATION_MODULE_ROOT_DIR ${CMAKE_SOURCE_DIR}/communication )

set(

  COMMUNICATION_MODULE_COMMON_HEADERS_DIRECTORIES

  ## IP ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/ip

  ## SOCKET ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/socket

  ## CONNECTION ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/connection

  ## SERVER ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/server

  ## PACKET ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/packet

  ## PROTOCOLS ##
  ${COMMUNICATION_MODULE_ROOT_DIR}/include/protocols

)

add_library(

  EXPORT_COMMUNICATION_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

)

target_include_directories(

  EXPORT_COMMUNICATION_MODULE_COMMON_HEADERS_DIRECTORIES INTERFACE

  ${COMMUNICATION_MODULE_COMMON_HEADERS_DIRECTORIES}

)
